CREATE DATABASE APLICACIONFACTURACION CHARACTER SET utf8 COLLATE utf8_bin;
USE DATABASE APLICACIONFACTURACION;
CREATE TABLE PROVEEDORES(
    CODIGO INT NOT NULL PRIMARY KEY,
    CIF VARCHAR(15),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(40),
    DIRECCION VARCHAR(50),
    LOCALIDAD VARCHAR(50),
    PROVINCIA VARCHAR(30),
    DISTRITO VARCHAR(6),
    TELEFONOS VARCHAR(30),
    FAX VARCHAR(10),
    OBSERVACIONES VARCHAR(100),
    SALDO INT
);
CREATE TABLE CLIENTES(
    CODIGO INT NOT NULL PRIMARY KEY,
    CIF VARCHAR(15),
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(40),
    DIRECCION VARCHAR(50),
    LOCALIDAD VARCHAR(50),
    PROVINCIA VARCHAR(30),
    DISTRITO VARCHAR(6),
    TELEFONOS VARCHAR(30),
    FAX VARCHAR(10),
    OBSERVACIONES VARCHAR(100),
    SALDO INT
);
CREATE TABLE EMPRESA(
    CODIGO  VARCHAR(2) NOT NULL PRIMARY KEY,
    NOMBRE  VARCHAR(50),
    DIRECCION VARCHAR(50),
    LOCALIDAD VARCHAR(50),
    NIF VARCHAR(9),
    IVA INT,
    R_EQUIVALENCIA INT,
    OBSERVACIONES VARCHAR(100)
);
CREATE TABLE ALMACEN(
    REFERENCIA VARCHAR(15) NOT NULL PRIMARY KEY,
    DENOMINACION VARCHAR(50),
    FECHA DATE,
    PVP_TARIFA INT,
    PVP_MINIMO INT,
    PVP_COSTE INT,
    STOCK_MINIMO INT,
    EXISTENCIAS INT,
    UBICACION VARCHAR(30),
    MODELO VARCHAR(30),
    MEDIDAS VARCHAR(30),
    CARACTERISTICAS VARCHAR(100)
);
CREATE TABLE ALMACEN_PROVEEDORES(
    REF_ALM VARCHAR(15),
    COD_PROV INT,
    PRIMARY KEY(REF_ALM, COD_PROV),
    CONSTRAINT FK1
    FOREIGN KEY (REF_ALM) REFERENCES ALMACEN (REFERENCIA),
    CONSTRAINT FK2
    FOREIGN KEY (COD_PROV) REFERENCES PROVEEDORES(CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE APUNTES_CLIENTES(
    CODIGO INT PRIMARY KEY,
    CLIENTE INT,
    CONCEPTO VARCHAR(50),
    FECHA DATE,
    IMPORTE INT,
    DEBE_HABER VARCHAR(50) CHECK (DEBE_HABER="D" OR DEBE_HABER="H"),
    CONSTRAINT FK3
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE APUNTES_PROVEEDORES(
    CODIGO INT PRIMARY KEY,
    PROVEEDOR   INT,
    CONCEPTO VARCHAR(50),
    FECHA DATE,
    IMPORTE INT,
    DEBE_HABER VARCHAR(50) CHECK (DEBE_HABER="D" OR DEBE_HABER="H"),
    CONSTRAINT FK4
    FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDORES (CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE FACTURAS(
    NUM_FACTURA INT NOT NULL PRIMARY KEY,
    FECHA DATE,
    CLIENTE INT,
    OBSERVACIONES VARCHAR(100),
    DESCUENTO INT,
    IVA INT,
    R_EQUIVALENCIA INT,
    BASE_IMPONIBLE INT,
    CONSTRAINT FK5
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES (CODIGO)
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE DETALLE_FACTURAS(
    FACTURA INT NOT NULL,
    NUMERO_LINEA INT,
    REFERENCIA VARCHAR(15),
    CANTIDAD INT,
    PRIMARY KEY(FACTURA, NUMERO_LINEA),
    CONSTRAINT FK6
    FOREIGN KEY (FACTURA) REFERENCES FACTURAS(NUM_FACTURA),
    CONSTRAINT FK7
    FOREIGN KEY (REFERENCIA) REFERENCES ALMACEN(REFERENCIA)
    ON DELETE CASCADE ON UPDATE CASCADE
);
