CREATE DATABASE COCHES CHARACTER SET utf8 COLLATE utf8_bin;
USE COCHES;
CREATE TABLE CLIENTE(
    DNI VARCHAR(9) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(30),
    DIRECCION VARCHAR(50),
    TELEFONO VARCHAR(9)
);
CREATE TABLE COCHE(
    MATRICULA VARCHAR(7) NOT NULL PRIMARY KEY,
    MODELO VARCHAR(20),
    MARCA  VARCHAR(15),
    COLOR VARCHAR(20),
    TIPO VARCHAR(15),
    DNICLI VARCHAR(9),
    CONSTRAINT FK1
    FOREIGN KEY (DNICLI) REFERENCES CLIENTE (DNI)
);
CREATE TABLE COCHENUEVO(
    MATRICULA VARCHAR(7) NOT NULL PRIMARY KEY,
    UNIDADES INT,
    CONSTRAINT FK2
    FOREIGN KEY (MATRICULA) REFERENCES COCHE (MATRICULA)
);
CREATE TABLE COCHEUSADO(
    MATRICULA VARCHAR(7) NOT NULL PRIMARY KEY,
    KILOMETROS INT,
    CONSTRAINT FK3
    FOREIGN KEY (MATRICULA) REFERENCES COCHE (MATRICULA)
);
CREATE TABLE MECANICO(
    DNI VARCHAR(9) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(20),
    APELLIDOS VARCHAR(30),
    SALARIO INT,
    FEHCA_CONTRATACION DATE
);
CREATE TABLE REPARA(
    MATRICULA VARCHAR(7) NOT NULL,
    DNIMEC VARCHAR(9),
    FECHA DATE,
    HORAS INT,
    PRIMARY KEY(MATRICULA, DNIMEC),
    CONSTRAINT FK4 
    FOREIGN KEY (MATRICULA) REFERENCES COCHE (MATRICULA),
    CONSTRAINT FK5
    FOREIGN KEY (DNIMEC) REFERENCES MECANICO (DNI)
    );
/*4.10*/
CREATE DATABASE FUTBOL CHARACTER SET utf8 COLLATE utf8_bin;
USE FUTBOL;
CREATE TABLE EQUIPO(
    COD_EQUIPO VARCHAR(9) NOT NULL PRIMARY KEY,
    NOM_EQUIPO VARCHAR(15),
    NOM_ESTADIO VARCHAR(20),
    AFORO INT,
    CIUDAD VARCHAR(15),
    AÑO_FUNDACION DATE
    );
CREATE TABLE PARTIDO(
    COD_PARTIDO VARCHAR(9) NOT NULL PRIMARY KEY,
    FECHA DATE,
    GOLES_CASA INT,
    GOLES_EXTRANJERO INT
);
CREATE TABLE JUEGAN(
    COD_EQUIPO VARCHAR(9) NOT NULL,
    COD_PARTIDO VARCHAR(9) NOT NULL,
    PRIMARY KEY(COD_EQUIPO, COD_PARTIDO),
    CONSTRAINT FK1
    FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPO (COD_EQUIPO),
    CONSTRAINT FK2
    FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDO (COD_PARTIDO)
);
CREATE TABLE JUGADOR(
    COD_JUGADOR VARCHAR(9) NOT NULL,
    COD_EQUIPO VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(20),
    FECHA_NACIMIENTO DATE,
    POSICION VARCHAR(10),
    PRIMARY KEY(COD_JUGADOR, COD_EQUIPO),
    CONSTRAINT FK3
    FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPO (COD_EQUIPO)
);
CREATE TABLE PRESIDENTE(
    DNI VARCHAR(9) NOT NULL PRIMARY KEY,
    COD_EQUIPO VARCHAR(9),
    NOM_EQUIPO VARCHAR(15),
    APELLIDOS VARCHAR(30),
    NOMBRE VARCHAR(20),
    FECHA_NACIMIENTO DATE,
    CONSTRAINT FK4
    FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPO (COD_EQUIPO)
);
CREATE TABLE GOL(
    CODIGO VARCHAR(9) NOT NULL,
    COD_JUGADOR VARCHAR(9),
    COD_PARTIDO VARCHAR(9),
    MINUTO INT,
    DESCRIPCION VARCHAR(100),
    PRIMARY KEY(CODIGO, COD_JUGADOR, COD_PARTIDO),
    CONSTRAINT FK5
    FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADOR (COD_JUGADOR),
    CONSTRAINT FK6
    FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDO (COD_PARTIDO)
    );  