CREATE TABLE alumnos2 (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY ,
    nombre VARCHAR (50) NOT NULL ,
    apellido1 VARCHAR (50) NOT NULL ,
    apellido2 VARCHAR (50),
    email VARCHAR (50)
);
DELIMITER $$
DROP TRIGGER IF EXISTS crear_email$$
CREATE TRIGGER crear_email
AFTER INSERT
ON alumnos2 
FOR EACH ROW
BEGIN
    SET NEW.email = LOWER(CONCAT(NEW.nombre, '.', NEW.apellido1, '.', NEW.apellido2, "@fpzornotza.com"));
END$$
DELIMITER $$
DROP TRIGGER IF EXISTS AUMENTAR_NOTA$$
CREATE TRIGGER AUMENTAR_NOTA
BEFORE UPDATE
ON alumnos FOR EACH ROW
BEGIN
IF NEW.nota > OLD.nota THEN
SET NEW.nota=NEW.nota*1.10;
END IF;
END$$
