CREATE DATABASE EMPRESA333 CHARACTER SET utf8 COLLATE utf8_bin;
DROP DATABASE EMPRESA333;
DROP DATABASE IF EXISTS EMPRESA333;
CREATE DATABASE EMPRESA333 CHARACTER SET utf8 COLLATE utf8_bin;
USE EMPRESA333;
CREATE TABLE EMPLEADITO(
    COD_EMPLEADO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EMP VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(35) NULL,
    DEPARTAMENTO VARCHAR (20) DEFAULT 'Informatica',
    FECHA_NACIMIENTO DATE
);
ALTER TABLE EMPLEADITO
RENAME TO EMPLEADO;
ALTER TABLE EMPLEADO
ADD TELEFONO VARCHAR(9) NOT NULL,
ADD EMAIL VARCHAR(20) NULL;
ALTER TABLE EMPLEADO
DROP COLUMN EMAIL;
ALTER TABLE EMPLEADO
CHANGE COLUMN NOMBRE_EMP NOMBRE VARCHAR(20) NOT NULL;
ALTER TABLE EMPLEADO
DROP COLUMN DEPARTAMENTO;
CREATE TABLE DEPARTAMENTO(
    CODIGO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(50) DEFAULT "ES UN APARTAMENTO EN EL QUE SE HACEN COSAS"
);
ALTER TABLE DEPARTAMENTO 
ADD COLUMN COD_DEPARTAMENTO INT;
ALTER TABLE DEPARTAMENTO 
ADD CONSTRAINT FK1 FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGO);
ALTER TABLE EMPLEADO 
DROP COLUMN NOMBRE,
DROP COLUMN APELLIDO,
DROP COLUMN FECHA_NACIMIENTO,
DROP COLUMN TELEFONO;
DROP TABLES EMPLEADO, DEPARTAMENTO;
