CREATE DATABASE SUMINISTROS CHARACTER SET utf8 COLLATE utf8_bin;
USE SUMINISTROS;
CREATE TABLE PIEZAS(
    PZ VARCHAR(4) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(10),
    COLOR VARCHAR(10),
    PESO INT,
    CIUDAD VARCHAR(20)
);
CREATE TABLE PROVEEDORES(
    PR VARCHAR(4) AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20),
    CANTIDAD INT,
    CIUDAD VARCHAR(20)
);
CREATE TABLE SUMINISTROS(
    PR VARCHAR(4),
    PZ VARCHAR(4),
    CANTIDAD INT,
    PRIMARY KEY(PR, PZ),
    FOREIGN KEY (PR) REFERENCES PROVEEDORES (PR),
    FOREIGN KEY (PZ) REFERENCES PIEZAS(PZ)
);